export const Globals = {
    BOARD_WIDTH: 600,
    BOARD_HEIGHT: 400,
    PADDLE_WIDTH: 15,
    PADDLE_HEIGHT: 75,
    PADDLE_COLOR: "blue",
    PADDLE_SPEED: 10,
    PADDLE_INDENT: 10,
    BALL_DIMENSION: 15,
    BALL_COLOR: "yellow",
    BALL_SPEED: 5,
    BALL_MAXSPEED: 40,
    BALL_SPEED_INCREMENT: 5,
};
